runtime: nodejs20
service: tugasin-fe
instance_class: F1

handlers:
  # Static assets (js, css, images)
  - url: /(.*\.(js|css|png|jpg|ico|json|map))
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|ico|json|map)

  # All other URLs route to index.html for React Router
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

default_expiration: "1h"